easy_admin:
   entities:
       # List the entity class name you want to manage
       - App\Entity\User
       - App\Entity\UserType
       - App\Entity\Poste
       - App\Entity\Techno
       - App\Entity\Adress